# A sample Gemfile
source 'http://rubygems.org'
source 'http://gems.github.com'

gem "eventmachine"
gem "nokogiri" # used by the itunes scraper
gem "chipmunk-ffi"
gem "eventmachine_httpserver"
gem "json"
